### ISSUE TITLE
Ext2 Boot Clarifications

### ISSUE THREAD

**Issue by Daxiongmao87** [alex-kas/nec_terrain#3]
Hey Alex,
Thanks for developing these boot options.  Im trying your method to format my system and data folder to ext2.  On the forum you mention to download the special boot image (the one with ext2) then edit the init.rc file.

I was wondering if you could be more specific.  I don't know where I'm supposed to push the build.prop and boot image, and I don't know what line to edit in the init.rc.  Any help would be appreciated! thanks

**Comment by alex-kas** [comment]
I will update the pages shortly
