### ISSUE TITLE
Does this method work on all hardware/software revisions of the NEC Terrian?

### ISSUE THREAD

**Issue by daveloyall** [alex-kas/nec_terrain#7]
Hello!  @alex-kas, this looks like great work!  Thank you!

Has NEC or AT&T changed the software or hardware on the NEC Terrain to prevent the method described here from working?

If I buy a brand new NEC Terrain today, can I expect this method to work?

**Comment by alex-kas** [comment]
Well, I'm not aware about software changes. So, you can try :) I pretty much sure that not, but who knows.

**Comment by daveloyall** [comment]
Thanks for your reply!  Wait, are you pretty sure it will not work, or pretty sure that it will work?

**Comment by alex-kas** [comment]
I'm almost sure that no soft changes were done.

**Comment by daveloyall** [comment]
Ok, got it!
